sonar.projectKey=minhazul73_Temp2temP
sonar.organization=minhazul73


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Temp2temP
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8