name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5

      - name: Run Build Wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make clean && make

      - name: Verify Build Wrapper Output
        run: |
          if [ ! -f ${{ env.BUILD_WRAPPER_OUT_DIR }}/build-wrapper-dump.json ]; then
            echo "Error: build-wrapper-dump.json not found!";
            exit 1;
          fi

      - name: Run Tests
        run: |
          gcc -Wall -Wextra -I./include tests/test_converter.c src/converter.c -o tests/test_converter
          ./tests/test_converter

      - name: Install gcovr
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov gcovr

      - name: Build with Coverage
        run: |
          gcc -fprofile-arcs -ftest-coverage -Wall -Wextra -I./include \
              src/converter.c tests/test_converter.c -o tests/test_converter

      - name: Run Tests and Generate Coverage
        run: |
          ./tests/test_converter
          gcovr --exclude tests/ \
                --root . \
                --xml-pretty \
                --output coverage.xml

      - name: Verify Coverage File
        run: |
          if [ ! -f coverage.xml ]; then
            echo "##[error] Coverage file not generated!"
            exit 1
          fi
          cat coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectKey=minhazul73_Temp2temP
            -Dsonar.organization=minhazul73
            -Dsonar.cfamily.build-wrapper-output=build_wrapper_output
            # -Dsonar.coverageReportPaths=coverage.xml
            -Dsonar.c.file.suffixes=.c,.h
            -Dsonar.language=c
            -Dsonar.sources=src
            -Dsonar.tests=tests